### PR TITLE
allow `tex_str` syntax 

### PR DESCRIPTION
**Pull request by MasonProtter**
No pressure to merge this, just thought it was fun to play around with it.

### CODE REVIEW

**Comment by fonsp** [comment]
I forgot to mention the third reason on zulip: `_str` macros with interpolation are not reactive in pluto 🙈 until https://github.com/fonsp/Pluto.jl/pull/1032 is fixed. :((

**Comment by MasonProtter** [comment]
Aha, that explains some errors I saw when I was implementing the `_str` version!

**Comment by fonsp** [comment]
Can you also take a look at the original macro? Right now it uses the odd arguments as text segments, and the even arguments as slots. This works for `@tex("hello $(1) and $(2)!")` but not for:

`@tex("hello $(1)$(2)")`
`@tex("hello $(1) and $(2)")`
`@tex("$(1) and $(2)")`

etc

Instead, we should check for the argument type (`String` vs anything else) and build up the parts and slots manually. The JS code expects the parts and slots to 'interweave'

**Comment by MasonProtter** [comment]
Yeah, I can try something out.

**Pull request merged**
